version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/sites-conf:/etc/nginx/sites-available
      - ./nginx/sites-conf:/etc/nginx/sites-enabled
      - ./nginx/logs:/var/log/nginx
      - ./apps:/var/www
