version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/sites-conf:/etc/nginx/sites-available
      - ./nginx/sites-conf:/etc/nginx/sites-enabled
      - ./nginx/logs:/var/log/nginx
      - ./apps:/var/www

  app-alice:
    image: php:7.3-fpm
    volumes:
      - ./apps/alice.com:/var/www/alice.com
      - ./apps/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    tty: true

  app-bob:
    image: php:7.3-fpm
    volumes:
      - ./apps/bob.com:/var/www/bob.com
    tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: tob_wholesale
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./apps/alice.com/tob_wholesale.sql:/etc/tob_wholesale.sql

networks:
  default:
